### ISSUE TITLE
Add sort by download

### ISSUE THREAD

**Issue by jack5github** [Vanilagy/Marbleland#1]
I'm quite curious as to why this is not a feature in Marbleland. It will seriously help me sort through all of the levels and find the ones that are truly worth downloading.

**Comment by Vanilagy** [comment]
I didn't add it on release because it would've been a useless feature with little to none downloads on most levels. The feature itself would be easy to add, but I'm not sure if the numbers have much true meaning yet, given the short time this website's been out. I could imagine many levels high up in the search (whose names are early in the alphabet) have the most downloads right now.

Also, doing a batch download such as downloading all levels increments the download count for each level by one too, which means old levels would accumulate tons of downloads this way while new levels would remain at a lower count.

That's why I haven't added sort by downloads yet, because I felt like it wouldn't carry much meaning. If you have any suggestions how to make it work, please lemme know.

**Comment by jack5github** [comment]
To prevent the levels at the start of the alphabet from being downloaded, you could either sort the levels randomly or by upload/edit date as default. Alternatively, you could add a scoring system, where accounts can rate levels up or down, and also favourite levels to save them for later.

**Comment by Vanilagy** [comment]
It's added now!
